### ISSUE TITLE
error trying to reproduce trapezoid example on Python3.4/Windows ?!?

### ISSUE THREAD

**Issue by stonebig** [takluyver/nbconvert-reportlab#2]
I  download the "raw" "Trapezoid 20Rule.pdf"from Github, and it generates an error....

There is no issue when I open it with Jupyter after that failed try. strange.

Same after saving it again from my jupyter notebook session.

```
C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\notebooks\docs>jupyter nbconvert --to pdf-rl "Trapezoid Rule.ipynb"
[NbConvertApp] Converting notebook Trapezoid Rule.ipynb to pdf-rl
Traceback (most recent call last):
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\Scripts\jupyter-nbconvert.EXE\__main__.py", line 9, in <module>
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert\nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert\nbconvertapp.py", line 457, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert\nbconvertapp.py", line 428, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert\nbconvertapp.py", line 357, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert\exporters\exporter.py", line 165, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert\exporters\exporter.py", line 183, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert_reportlab\exporter.py", line 100, in from_notebook_node
    output = NbPdfConverter(nb_copy,  resources).go()
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert_reportlab\exporter.py", line 78, in go
    self.convert_markdown_cell(cell)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert_reportlab\exporter.py", line 43, in convert_markdown_cell
    self.pieces.extend(md_to_flowables(cell.source, self.stylesheet))
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert_reportlab\rlmarkdown.py", line 123, in md_to_flowables
    return converter.render(src)
  File "mistune.py", line 979, in mistune.Markdown.render (mistune.c:20052)
    return self.parse(text)
  File "mistune.py", line 982, in mistune.Markdown.parse (mistune.c:20424)
    out = self.output(preprocessing(text))
  File "mistune.py", line 1031, in mistune.Markdown.output (mistune.c:21332)
    out += self.tok()
  File "mistune.py", line 1041, in mistune.Markdown.tok (mistune.c:21494)
    return getattr(self, 'output_%s' % t)()
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert\filters\markdown_mistune.py", line 81, in output_block_math
    return self.renderer.block_math(self.token['text'])
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert_reportlab\rlmarkdown.py", line 115, in block_math
    img = PdfImage(f)
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\nbconvert_reportlab\pdfimage.py", line 33, in __init__
    page = PdfReader(filename_or_object, decompress=False).pages[0]
  File "C:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.5\python-3.4.4.amd64\lib\site-packages\pdfrw\pdfreader.py", line 499, in __init__
    if not fdata.startswith('%PDF-'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by takluyver** [comment]
Oh yeah, I forgot to say that - it requires installing pdfrw from master at the moment, because of issue pmaupin/pdfrw#51.

**Comment by stonebig** [comment]
indeed, it works now. thanks
